import React from 'react';
import { motion } from 'framer-motion';

const pageVariants = {
  initial: { opacity: 0, scale: 0.98, y: 10 },
  animate: { opacity: 1, scale: 1, y: 0 },
  exit: { opacity: 0, scale: 0.98, y: -10 }
};

const transitionAttr = { duration: 0.4, ease: [0.16, 1, 0.3, 1] };

export function AboutCFG() {
  return (
    <motion.div variants={pageVariants} initial="initial" animate="animate" exit="exit" transition={transitionAttr} className="glass-panel" style={{ padding: '32px', maxWidth: '800px', margin: '0 auto' }}>
      <h2 style={{ fontSize: '1.75rem', fontWeight: 800, marginBottom: '16px', color: 'var(--text-main)' }}>About Context-Free Grammar (CFG)</h2>
      <p style={{ color: 'var(--text-muted)', lineHeight: 1.6, marginBottom: '16px' }}>
        A Context-Free Grammar is a fundamental structure in formal language theory, utilized mathematically to generate strings in a specific formal language. A standard CFG is formally defined as a 4-tuple <strong style={{ color: 'var(--accent-secondary)' }}>G = (V, T, P, S)</strong> where:
      </p>
      <ul style={{ paddingLeft: '24px', color: 'var(--text-muted)', lineHeight: 1.6, marginBottom: '24px' }}>
        <li style={{ marginBottom: '8px' }}><strong>V (Variables/Non-terminals):</strong> A finite, non-empty set of symbols representing syntactic categories or sub-trees in the language.</li>
        <li style={{ marginBottom: '8px' }}><strong>T (Terminals):</strong> A finite, non-empty set of basic symbols from which the actual output strings are formed. By definition, variables and terminals must be disjoint sets (V &cap; T = &empty;).</li>
        <li style={{ marginBottom: '8px' }}><strong>P (Productions):</strong> A finite set of production mapping rules taking the form <em>A &rarr; &alpha;</em>, where A is exactly one variable, and &alpha; is any continuous string composed of variables and/or terminals.</li>
        <li><strong>S (Start Symbol):</strong> A specialized non-terminal serving as the immutable root of the grammar tree. All valid words generated by the language begin their derivation sequence from S.</li>
      </ul>
      <h3 style={{ fontSize: '1.25rem', fontWeight: 600, marginBottom: '12px', color: 'var(--text-main)' }}>The "Context-Free" Designation</h3>
      <p style={{ color: 'var(--text-muted)', lineHeight: 1.6 }}>
        The descriptor "context-free" originates purely from the production rules. In entirely context-free grammars, the left constraint of any production is strictly limited to an isolated, single Non-Terminal variable. This guarantees that whenever a grammar derives a string, any specific variable can instantly be recursively rewritten with its right-hand rule regardless of adjacent terminals—irrespective of its "context". 
      </p>
    </motion.div>
  );
}

export function WhatIsCNF() {
  return (
    <motion.div variants={pageVariants} initial="initial" animate="animate" exit="exit" transition={transitionAttr} className="glass-panel" style={{ padding: '32px', maxWidth: '800px', margin: '0 auto' }}>
      <h2 style={{ fontSize: '1.75rem', fontWeight: 800, marginBottom: '16px', color: 'var(--text-main)' }}>What is CNF?</h2>
      <p style={{ color: 'var(--text-muted)', lineHeight: 1.6, marginBottom: '16px' }}>
        Chomsky Normal Form (CNF) is a highly restrictive, computationally optimal structure for context-free grammars. It enforces a mathematically uniform structure, guaranteeing that syntax trees formulated under CNF are pure binary trees. A grammar resides strictly in Chomsky Normal Form if, and only if, every single production rule assumes one of two identical configurations:
      </p>
      <div style={{ background: 'var(--code-bg)', padding: '16px', borderRadius: '8px', marginBottom: '24px', border: '1px solid var(--border-glass)' }}>
        <ul style={{ listStyle: 'none', padding: 0, color: 'var(--code-text)', fontFamily: 'monospace', fontSize: '1.1rem' }}>
          <li style={{ marginBottom: '8px' }}>1. <span style={{ color: 'var(--accent-primary)', fontWeight: 'bold' }}>A</span> &rarr; <span style={{ color: 'var(--accent-primary)', fontWeight: 'bold' }}>B C</span>  (A variable derives exactly two variables)</li>
          <li>2. <span style={{ color: 'var(--accent-primary)', fontWeight: 'bold' }}>A</span> &rarr; <span style={{ color: 'var(--code-term)' }}>a</span>     (A variable derives exactly one terminal)</li>
        </ul>
      </div>
      <h3 style={{ fontSize: '1.25rem', fontWeight: 600, marginBottom: '12px', color: 'var(--text-main)' }}>Mathematical Bounds</h3>
      <p style={{ color: 'var(--text-muted)', lineHeight: 1.6 }}>
        Structurally limiting grammar to CNF ensures immense algorithmic determinism. Due to the strict binary derivations, any valid string <em>w</em> of length <em>n</em> within the language will predictably require exactly <em>2n - 1</em> derivation steps to generate entirely. Furthermore, the parse tree will contain precisely <em>2n - 1</em> total nodes. This deterministic property acts as the foundational mechanism behind matrix-based language recognition algorithms, such as the Cocke-Younger-Kasami (CYK) algorithm.
      </p>
    </motion.div>
  );
}

export function StepsCNF() {
  return (
    <motion.div variants={pageVariants} initial="initial" animate="animate" exit="exit" transition={transitionAttr} className="glass-panel" style={{ padding: '32px', maxWidth: '800px', margin: '0 auto' }}>
      <h2 style={{ fontSize: '1.75rem', fontWeight: 800, marginBottom: '16px', color: 'var(--text-main)' }}>Steps of converting CFG to CNF</h2>
      <p style={{ color: 'var(--text-muted)', lineHeight: 1.6, marginBottom: '24px' }}>
        The conversion to Chomsky Normal Form follows a mathematically rigorous 6-step pipeline to ensure the grammar is reduced to binary and terminal productions:
      </p>
      
      <ol style={{ paddingLeft: '24px', color: 'var(--text-muted)', lineHeight: 1.6, marginBottom: '24px' }}>
        <li style={{ marginBottom: '16px' }}>
          <strong style={{ color: 'var(--text-main)' }}>Preprocessing (Start Symbol Augmentation):</strong>
          <br/>To ensure the start variable never appears on the right-hand side, a new start symbol <em>S<sub>0</sub></em> is introduced with the production <em>S<sub>0</sub> &rarr; S</em>.
        </li>
        <li style={{ marginBottom: '16px' }}>
          <strong style={{ color: 'var(--text-main)' }}>Epsilon (&epsilon;) Elimination:</strong>
          <br/>Nullable variables are identified. New productions are generated by calculating the power-set of all possible combinations for each rule containing nullable variables.
        </li>
        <li style={{ marginBottom: '16px' }}>
          <strong style={{ color: 'var(--text-main)' }}>Unit Production Elimination:</strong>
          <br/>Unit productions (A &rarr; B) are removed by computing the transitive closure of all unit chains and replacing them with non-unit terminal/binary derivations.
        </li>
        <li style={{ marginBottom: '16px' }}>
          <strong style={{ color: 'var(--text-main)' }}>Useless Symbol Removal:</strong>
          <br/>Non-generating variables (those that cannot derive a terminal string) and unreachable variables (those that cannot be reached from the start symbol) are pruned.
        </li>
        <li style={{ marginBottom: '16px' }}>
          <strong style={{ color: 'var(--text-main)' }}>Terminal Replacement:</strong>
          <br/>For any production rule with length &ge; 2, every terminal <em>a</em> is replaced by a unique proxy variable <em>T<sub>a</sub></em> to ensure no terminals mix with variables.
        </li>
        <li style={{ marginBottom: '8px' }}>
          <strong style={{ color: 'var(--text-main)' }}>Binarization:</strong>
          <br/>Long productions are broken down into cascading binary chains. For example, <em>A &rarr; BCD</em> is transformed into <em>A &rarr; BX</em> and <em>X &rarr; CD</em>.
        </li>
      </ol>
    </motion.div>
  );
}

export function WhatIsGNF() {
  return (
    <motion.div variants={pageVariants} initial="initial" animate="animate" exit="exit" transition={transitionAttr} className="glass-panel" style={{ padding: '32px', maxWidth: '800px', margin: '0 auto' }}>
      <h2 style={{ fontSize: '1.75rem', fontWeight: 800, marginBottom: '16px', color: 'var(--text-main)' }}>What is GNF?</h2>
      <p style={{ color: 'var(--text-muted)', lineHeight: 1.6, marginBottom: '16px' }}>
        Greibach Normal Form (GNF) is a specialized configuration where every production rule starts strictly with exactly one terminal. This structure is essential for constructing Pushdown Automata and efficient Top-Down parsing.
      </p>
      <div style={{ background: 'var(--code-bg)', padding: '16px', borderRadius: '8px', marginBottom: '24px', border: '1px solid var(--border-glass)' }}>
        <p style={{ margin: 0, color: 'var(--code-text)', fontFamily: 'monospace', fontSize: '1.1rem' }}>
          <span style={{ color: 'var(--accent-primary)', fontWeight: 'bold' }}>A</span> &rarr; <span style={{ color: 'var(--code-term)' }}>a</span> <span style={{ color: 'var(--accent-primary)', fontWeight: 'bold' }}>V<sub>1</sub> V<sub>2</sub> ... V<sub>n</sub></span>
        </p>
      </div>
      <p style={{ color: 'var(--text-muted)', lineHeight: 1.6, marginBottom: '16px' }}>
        In GNF, the right-hand side must begin with a terminal character (lowercase), followed by any number of non-terminal variables (uppercase). This layout eliminates left-recursion and guarantees path determinism.
      </p>
      <h3 style={{ fontSize: '1.25rem', fontWeight: 600, marginBottom: '12px', color: 'var(--text-main)' }}>Theoretical Utility</h3>
      <p style={{ color: 'var(--text-muted)', lineHeight: 1.6 }}>
        GNF ensures that for every derivation step, exactly one input character is consumed from the string being parsed. This 1-to-1 mapping between terminals and transitions provides the mathematical foundation for converting context-free languages into hardware-level state machines.
      </p>
    </motion.div>
  );
}

export function StepsGNF() {
  return (
    <motion.div variants={pageVariants} initial="initial" animate="animate" exit="exit" transition={transitionAttr} className="glass-panel" style={{ padding: '32px', maxWidth: '800px', margin: '0 auto' }}>
      <h2 style={{ fontSize: '1.75rem', fontWeight: 800, marginBottom: '16px', color: 'var(--text-main)' }}>Steps of converting CFG to GNF</h2>
      <p style={{ color: 'var(--text-muted)', lineHeight: 1.6, marginBottom: '24px' }}>
        Achieving Greibach Normal Form involves a complex 9-step procedure utilizing variable ordering and recursive substitution:
      </p>
      
      <ol style={{ paddingLeft: '24px', color: 'var(--text-muted)', lineHeight: 1.6, marginBottom: '24px' }}>
        <li style={{ marginBottom: '12px' }}>
          <strong style={{ color: 'var(--text-main)' }}>Preprocessing:</strong>
          <br/>Initial grammar cleanup and addition of a root start symbol to isolate derivation cycles.
        </li>
        <li style={{ marginBottom: '12px' }}>
          <strong style={{ color: 'var(--text-main)' }}>Epsilon (&epsilon;) Elimination:</strong>
          <br/>Removal of all empty transitions by expanding rule combinations.
        </li>
        <li style={{ marginBottom: '12px' }}>
          <strong style={{ color: 'var(--text-main)' }}>Unit Production Removal:</strong>
          <br/>Substitution of all single-variable rules with their terminal or binary leaves.
        </li>
        <li style={{ marginBottom: '12px' }}>
          <strong style={{ color: 'var(--text-main)' }}>Useless Symbol Removal:</strong>
          <br/>Pruning of non-generating and unreachable variables to reduce state complexity.
        </li>
        <li style={{ marginBottom: '12px' }}>
          <strong style={{ color: 'var(--text-main)' }}>CNF Preparation:</strong>
          <br/>Converting the grammar to Chomsky Normal Form (binarization) to standardize the rule length.
        </li>
        <li style={{ marginBottom: '12px' }}>
          <strong style={{ color: 'var(--text-main)' }}>Variable Ordering:</strong>
          <br/>Variables are strictly ordered (A<sub>1</sub> &lt; A<sub>2</sub> &lt; ... &lt; A<sub>n</sub>) to detect indirect cycles.
        </li>
        <li style={{ marginBottom: '12px' }}>
          <strong style={{ color: 'var(--text-main)' }}>Left Recursion Removal:</strong>
          <br/>Direct left recursion (A<sub>i</sub> &rarr; A<sub>i</sub> &alpha;) is eliminated using new sub-indexed variables (Z<sub>i</sub>).
        </li>
        <li style={{ marginBottom: '12px' }}>
          <strong style={{ color: 'var(--text-main)' }}>Leading Variable Substitution:</strong>
          <br/>Forward and backward substitution from A<sub>n</sub> down to A<sub>1</sub> to force all rules to begin with terminals.
        </li>
        <li style={{ marginBottom: '8px' }}>
          <strong style={{ color: 'var(--text-main)' }}>Final GNF Enforcement:</strong>
          <br/>Propagating terminal-first substitutions across all rules to satisfy Greibach's formal criteria.
        </li>
      </ol>
    </motion.div>
  );
}
